lang:String
export type Lang = "pt" | "en" | "fr";

export const translations: Record<Lang, Record<string, string>> = {
  pt: {
    welcome: "Bem-vindo ao Seatify",
    subtitle: "Tecnologia Kori para a sua melhor experiência gastronómica",
    getStarted: "Começar",
    chooseLang: "Escolha o seu idioma",
    chooseLangSub: "Selecione a língua que prefere usar",
    continue: "Continuar",
    tables: "Mesas",
    free: "Livre",
    occupied: "Ocupada",
    reserved: "Reservada",
    restaurant: "Restaurante",
    location: "Localização",
    all: "Todos",
    overview: "Visão geral",
    filters: "Filtros",
    map: "Mapa",
    grid: "Grelha",
    seats: "lugares",
    table: "Mesa",
    occupancy: "Ocupação",
    avgTime: "Tempo médio",
    today: "Hoje",
    minutes: "min",
    bookTable: "Reservar mesa",
    viewDetails: "Ver detalhes",
    nearby: "Restaurantes próximos",
    rating: "Avaliação",
    open: "Aberto",
    closed: "Fechado",
    back: "Voltar",
    reserve: "Reservar",
    reserveTable: "Reservar mesa",
    pickDate: "Escolha a data",
    pickTime: "Escolha o horário",
    guests: "Convidados",
    guestName: "Nome",
    guestPhone: "Telefone",
    confirm: "Confirmar reserva",
    cancel: "Cancelar",
    reservationConfirmed: "Reserva confirmada!",
    reservationDetails: "Detalhes da reserva",
    showRoute: "Ver rota",
    hideRoute: "Esconder rota",
    distance: "Distância",
    duration: "Tempo",
    km: "km",
    cuisine: "Cozinha",
    status: "Estado",
    sortBy: "Ordenar por",
    sortRating: "Avaliação",
    sortName: "Nome",
    sortDistance: "Distância",
    noResults: "Sem resultados",
    clearFilters: "Limpar filtros",
    onlyOpen: "Apenas abertos",
    yourLocation: "A sua localização",
    locating: "A obter localização...",
    routeError: "Não foi possível calcular a rota",
  },
  en: {
    welcome: "Welcome to Seatify",
    subtitle: "Kori technology for your best dining experience",
    getStarted: "Get started",
    chooseLang: "Choose your language",
    chooseLangSub: "Select the language you prefer",
    continue: "Continue",
    tables: "Tables",
    free: "Free",
    occupied: "Occupied",
    reserved: "Reserved",
    restaurant: "Restaurant",
    location: "Location",
    all: "All",
    overview: "Overview",
    filters: "Filters",
    map: "Map",
    grid: "Grid",
    seats: "seats",
    table: "Table",
    occupancy: "Occupancy",
    avgTime: "Avg. time",
    today: "Today",
    minutes: "min",
    bookTable: "Book table",
    viewDetails: "View details",
    nearby: "Nearby restaurants",
    rating: "Rating",
    open: "Open",
    closed: "Closed",
    back: "Back",
    reserve: "Reserve",
    reserveTable: "Reserve table",
    pickDate: "Pick a date",
    pickTime: "Pick a time",
    guests: "Guests",
    guestName: "Name",
    guestPhone: "Phone",
    confirm: "Confirm booking",
    cancel: "Cancel",
    reservationConfirmed: "Booking confirmed!",
    reservationDetails: "Booking details",
    showRoute: "Show route",
    hideRoute: "Hide route",
    distance: "Distance",
    duration: "Time",
    km: "km",
    cuisine: "Cuisine",
    status: "Status",
    sortBy: "Sort by",
    sortRating: "Rating",
    sortName: "Name",
    sortDistance: "Distance",
    noResults: "No results",
    clearFilters: "Clear filters",
    onlyOpen: "Only open",
    yourLocation: "Your location",
    locating: "Getting location...",
    routeError: "Could not compute route",
  },
  fr: {
    welcome: "Bienvenue sur Seatify",
    subtitle: "Technologie Kori pour votre meilleure expérience gastronomique",
    getStarted: "Commencer",
    chooseLang: "Choisissez votre langue",
    chooseLangSub: "Sélectionnez la langue que vous préférez",
    continue: "Continuer",
    tables: "Tables",
    free: "Libre",
    occupied: "Occupée",
    reserved: "Réservée",
    restaurant: "Restaurant",
    location: "Lieu",
    all: "Tous",
    overview: "Aperçu",
    filters: "Filtres",
    map: "Carte",
    grid: "Grille",
    seats: "places",
    table: "Table",
    occupancy: "Occupation",
    avgTime: "Temps moy.",
    today: "Aujourd'hui",
    minutes: "min",
    bookTable: "Réserver",
    viewDetails: "Voir détails",
    nearby: "Restaurants à proximité",
    rating: "Note",
    open: "Ouvert",
    closed: "Fermé",
    back: "Retour",
    reserve: "Réserver",
    reserveTable: "Réserver une table",
    pickDate: "Choisissez la date",
    pickTime: "Choisissez l'heure",
    guests: "Convives",
    guestName: "Nom",
    guestPhone: "Téléphone",
    confirm: "Confirmer",
    cancel: "Annuler",
    reservationConfirmed: "Réservation confirmée !",
    reservationDetails: "Détails de la réservation",
    showRoute: "Voir itinéraire",
    hideRoute: "Cacher itinéraire",
    distance: "Distance",
    duration: "Durée",
    km: "km",
    cuisine: "Cuisine",
    status: "Statut",
    sortBy: "Trier par",
    sortRating: "Note",
    sortName: "Nom",
    sortDistance: "Distance",
    noResults: "Aucun résultat",
    clearFilters: "Effacer filtres",
    onlyOpen: "Ouverts seulement",
    yourLocation: "Votre position",
    locating: "Localisation...",
    routeError: "Impossible de calculer l'itinéraire",
  },
};

export interface Restaurant {
  id: string;
  name: string;
  city: string;
  address: string;
  image: string;
  rating: number;
  open: boolean;
  lat: number;
  lng: number;
  cuisine: string;
}

export const restaurants: Restaurant[] = [
  {
    id: "r1",
    name: "Belcanto",
    city: "Lisboa",
    address: "Largo de São Carlos 10, Chiado",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
    rating: 4.9,
    open: true,
    lat: 38.7102,
    lng: -9.1419,
    cuisine: "Contemporânea",
  },
  {
    id: "r2",
    name: "Cervejaria Ramiro",
    city: "Lisboa",
    address: "Av. Almirante Reis 1, Intendente",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    rating: 4.7,
    open: true,
    lat: 38.7223,
    lng: -9.1352,
    cuisine: "Marisco",
  },
  {
    id: "r3",
    name: "The Yeatman",
    city: "Porto",
    address: "R. do Choupelo, V.N. Gaia",
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800&q=80",
    rating: 4.8,
    open: true,
    lat: 41.1376,
    lng: -8.6175,
    cuisine: "Fine dining",
  },
  {
    id: "r4",
    name: "Cantinho do Avillez",
    city: "Porto",
    address: "R. Mouzinho da Silveira 166",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
    rating: 4.6,
    open: false,
    lat: 41.1437,
    lng: -8.6131,
    cuisine: "Portuguesa",
  },
  {
    id: "r5",
    name: "Sála",
    city: "Lisboa",
    address: "R. dos Bacalhoeiros 103",
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80",
    rating: 4.7,
    open: true,
    lat: 38.7095,
    lng: -9.1331,
    cuisine: "Autoral",
  },
];

export type TableStatus = "free" | "occupied" | "reserved";
export interface RTable {
  id: string;
  number: number;
  seats: number;
  status: TableStatus;
  zone: string;
}

export function generateTables(seed: string): RTable[] {
  const zones = ["Salão", "Esplanada", "Privado"];
  // pseudo-random based on seed
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  const rand = () => {
    h = (h * 1664525 + 1013904223) >>> 0;
    return h / 0xffffffff;
  };
  return Array.from({ length: 18 }, (_, i) => {
    const r = rand();
    const status: TableStatus = r < 0.45 ? "free" : r < 0.85 ? "occupied" : "reserved";
    return {
      id: `t${i + 1}`,
      number: i + 1,
      seats: [2, 2, 4, 4, 4, 6, 8][Math.floor(rand() * 7)],
      status,
      zone: zones[Math.floor(rand() * zones.length)],
    };
  });
}